-- Filet Render : colonnes Event attendues par le client Prisma.
-- wanted / allowGroups n'ont jamais eu de migration : findMany et le seed 500.
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "zone" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "venue" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "endsAt" TIMESTAMP(3);
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "priceXaf" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'XAF';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "capacity" INTEGER;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "minAge" INTEGER;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "requiresReservation" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "paymentRule" TEXT NOT NULL DEFAULT 'HOLD';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "wanted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "allowGroups" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "recurrence" TEXT NOT NULL DEFAULT 'NONE';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "seriesId" TEXT;
