export const adminCopy = {
  command: "TipTop Command Center",
  subtitle: "Cerveau opérationnel — données réelles, jamais de faux « connecté ».",
  search: "Recherche globale",
  searchHint: "Utilisateur, sortie, billet, paiement, signalement…",
  alerts: "Alertes",
  users: "Utilisateurs",
  organizers: "Organisateurs",
  events: "Sorties",
  tickets: "Billets & réservations",
  finance: "Finance",
  refunds: "Remboursements",
  moderation: "Modération",
  ai: "IA",
  notifications: "Notifications",
  world: "Monde & missions",
  messaging: "Messagerie",
  analytics: "Analytics",
  flags: "Feature flags",
  settings: "Paramètres",
  services: "Services",
  setup: "Assistant config",
  webhooks: "Webhooks",
  audit: "Audit",
  alertsPage: "Alertes",
  support: "Support",
  maps: "Cartes",
  phone: "Auth téléphone",
  firebase: "Firebase",
  preview: "Aperçu app",
  save: "Enregistrer",
  confirmAll: "Confirmer l’envoi à tous",
  mockLedger: "Ledger mock — pas de Stripe",
  noFirebase: "Firebase n’est pas dans TipTop",
  noGoogleMaps: "Google Maps n’est pas branché (Nominatim)",
} as const;

export const NAV = [
  { href: "/admin", label: "Dashboard" },
  { href: "/admin/alerts", label: "Alerts" },
  { href: "/admin/support", label: "Support" },
  { href: "/admin/users", label: "Users" },
  { href: "/admin/organizers", label: "Organizers" },
  { href: "/admin/events", label: "Events" },
  { href: "/admin/tickets", label: "Tickets" },
  { href: "/admin/finance", label: "Finance" },
  { href: "/admin/refunds", label: "Refunds" },
  { href: "/admin/moderation", label: "Moderation" },
  { href: "/admin/reports", label: "Reports" },
  { href: "/admin/posts", label: "Posts" },
  { href: "/admin/moods", label: "Moods" },
  { href: "/admin/ai", label: "AI" },
  { href: "/admin/notifications", label: "Notifications" },
  { href: "/admin/world", label: "World" },
  { href: "/admin/messaging", label: "Messaging" },
  { href: "/admin/analytics", label: "Analytics" },
  { href: "/admin/flags", label: "Flags" },
  { href: "/admin/settings", label: "Settings" },
  { href: "/admin/services", label: "Services" },
  { href: "/admin/setup", label: "Setup" },
  { href: "/admin/maps", label: "Maps" },
  { href: "/admin/phone-auth", label: "Phone" },
  { href: "/admin/firebase", label: "Firebase" },
  { href: "/admin/webhooks", label: "Webhooks" },
  { href: "/admin/audit", label: "Audit" },
  { href: "/admin/likes", label: "Likes" },
  { href: "/admin/payments", label: "Ledger" },
] as const;
